//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.PagosMacul {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaginaRedireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PaginaRedireccion {
            get {
                return this.PaginaRedireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginaRedireccionField, value) != true)) {
                    this.PaginaRedireccionField = value;
                    this.RaisePropertyChanged("PaginaRedireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IdExt {
            get {
                return this.IdExtField;
            }
            set {
                if ((object.ReferenceEquals(this.IdExtField, value) != true)) {
                    this.IdExtField = value;
                    this.RaisePropertyChanged("IdExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Org {
            get {
                return this.OrgField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgField, value) != true)) {
                    this.OrgField = value;
                    this.RaisePropertyChanged("Org");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", ConfigurationName="PagosMacul.ServicioSoap")]
    public interface ServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento motivoCobro del espacio de nombres https://200.54.162.185/BotonTGR/Servicio/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/EnviaGiro", ReplyAction="*")]
        SocialAseoWeb.PagosMacul.EnviaGiroResponse EnviaGiro(SocialAseoWeb.PagosMacul.EnviaGiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/EnviaGiro", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaGiroResponse> EnviaGiroAsync(SocialAseoWeb.PagosMacul.EnviaGiroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento M2 del espacio de nombres https://200.54.162.185/BotonTGR/Servicio/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/RecibePago", ReplyAction="*")]
        SocialAseoWeb.PagosMacul.RecibePagoResponse RecibePago(SocialAseoWeb.PagosMacul.RecibePagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/RecibePago", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibePagoResponse> RecibePagoAsync(SocialAseoWeb.PagosMacul.RecibePagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecInforma del espacio de nombres https://200.54.162.185/BotonTGR/Servicio/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/EnviaCuadratura", ReplyAction="*")]
        SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse EnviaCuadratura(SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/EnviaCuadratura", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse> EnviaCuadraturaAsync(SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MR del espacio de nombres https://200.54.162.185/BotonTGR/Servicio/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/RecibeCuadratura", ReplyAction="*")]
        SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse RecibeCuadratura(SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/RecibeCuadratura", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse> RecibeCuadraturaAsync(SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloMyFriendResult del espacio de nombres https://200.54.162.185/BotonTGR/Servicio/Service.asmx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/HelloMyFriend", ReplyAction="*")]
        SocialAseoWeb.PagosMacul.HelloMyFriendResponse HelloMyFriend(SocialAseoWeb.PagosMacul.HelloMyFriendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://200.54.162.185/BotonTGR/Servicio/Service.asmx/HelloMyFriend", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.HelloMyFriendResponse> HelloMyFriendAsync(SocialAseoWeb.PagosMacul.HelloMyFriendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaGiroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaGiro", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.EnviaGiroRequestBody Body;
        
        public EnviaGiroRequest() {
        }
        
        public EnviaGiroRequest(SocialAseoWeb.PagosMacul.EnviaGiroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class EnviaGiroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string motivoCobro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vencimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string movimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string folioTGR;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rutCont;
        
        public EnviaGiroRequestBody() {
        }
        
        public EnviaGiroRequestBody(string motivoCobro, decimal monto, string vencimiento, string movimiento, string folioTGR, string rutCont) {
            this.motivoCobro = motivoCobro;
            this.monto = monto;
            this.vencimiento = vencimiento;
            this.movimiento = movimiento;
            this.folioTGR = folioTGR;
            this.rutCont = rutCont;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaGiroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaGiroResponse", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.EnviaGiroResponseBody Body;
        
        public EnviaGiroResponse() {
        }
        
        public EnviaGiroResponse(SocialAseoWeb.PagosMacul.EnviaGiroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class EnviaGiroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocialAseoWeb.PagosMacul.Respuesta EnviaGiroResult;
        
        public EnviaGiroResponseBody() {
        }
        
        public EnviaGiroResponseBody(SocialAseoWeb.PagosMacul.Respuesta EnviaGiroResult) {
            this.EnviaGiroResult = EnviaGiroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibePagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibePago", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.RecibePagoRequestBody Body;
        
        public RecibePagoRequest() {
        }
        
        public RecibePagoRequest(SocialAseoWeb.PagosMacul.RecibePagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class RecibePagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string M2;
        
        public RecibePagoRequestBody() {
        }
        
        public RecibePagoRequestBody(string M2) {
            this.M2 = M2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibePagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibePagoResponse", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.RecibePagoResponseBody Body;
        
        public RecibePagoResponse() {
        }
        
        public RecibePagoResponse(SocialAseoWeb.PagosMacul.RecibePagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class RecibePagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecibePagoResult;
        
        public RecibePagoResponseBody() {
        }
        
        public RecibePagoResponseBody(string RecibePagoResult) {
            this.RecibePagoResult = RecibePagoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCuadraturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCuadratura", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.EnviaCuadraturaRequestBody Body;
        
        public EnviaCuadraturaRequest() {
        }
        
        public EnviaCuadraturaRequest(SocialAseoWeb.PagosMacul.EnviaCuadraturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class EnviaCuadraturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecInforma;
        
        public EnviaCuadraturaRequestBody() {
        }
        
        public EnviaCuadraturaRequestBody(string fecInforma) {
            this.fecInforma = fecInforma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaCuadraturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaCuadraturaResponse", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.EnviaCuadraturaResponseBody Body;
        
        public EnviaCuadraturaResponse() {
        }
        
        public EnviaCuadraturaResponse(SocialAseoWeb.PagosMacul.EnviaCuadraturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class EnviaCuadraturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaCuadraturaResult;
        
        public EnviaCuadraturaResponseBody() {
        }
        
        public EnviaCuadraturaResponseBody(string EnviaCuadraturaResult) {
            this.EnviaCuadraturaResult = EnviaCuadraturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibeCuadraturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibeCuadratura", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.RecibeCuadraturaRequestBody Body;
        
        public RecibeCuadraturaRequest() {
        }
        
        public RecibeCuadraturaRequest(SocialAseoWeb.PagosMacul.RecibeCuadraturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class RecibeCuadraturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MR;
        
        public RecibeCuadraturaRequestBody() {
        }
        
        public RecibeCuadraturaRequestBody(string MR) {
            this.MR = MR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibeCuadraturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibeCuadraturaResponse", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.RecibeCuadraturaResponseBody Body;
        
        public RecibeCuadraturaResponse() {
        }
        
        public RecibeCuadraturaResponse(SocialAseoWeb.PagosMacul.RecibeCuadraturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class RecibeCuadraturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecibeCuadraturaResult;
        
        public RecibeCuadraturaResponseBody() {
        }
        
        public RecibeCuadraturaResponseBody(string RecibeCuadraturaResult) {
            this.RecibeCuadraturaResult = RecibeCuadraturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloMyFriendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloMyFriend", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.HelloMyFriendRequestBody Body;
        
        public HelloMyFriendRequest() {
        }
        
        public HelloMyFriendRequest(SocialAseoWeb.PagosMacul.HelloMyFriendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloMyFriendRequestBody {
        
        public HelloMyFriendRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloMyFriendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloMyFriendResponse", Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx", Order=0)]
        public SocialAseoWeb.PagosMacul.HelloMyFriendResponseBody Body;
        
        public HelloMyFriendResponse() {
        }
        
        public HelloMyFriendResponse(SocialAseoWeb.PagosMacul.HelloMyFriendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://200.54.162.185/BotonTGR/Servicio/Service.asmx")]
    public partial class HelloMyFriendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloMyFriendResult;
        
        public HelloMyFriendResponseBody() {
        }
        
        public HelloMyFriendResponseBody(string HelloMyFriendResult) {
            this.HelloMyFriendResult = HelloMyFriendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : SocialAseoWeb.PagosMacul.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<SocialAseoWeb.PagosMacul.ServicioSoap>, SocialAseoWeb.PagosMacul.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.PagosMacul.EnviaGiroResponse SocialAseoWeb.PagosMacul.ServicioSoap.EnviaGiro(SocialAseoWeb.PagosMacul.EnviaGiroRequest request) {
            return base.Channel.EnviaGiro(request);
        }
        
        public SocialAseoWeb.PagosMacul.Respuesta EnviaGiro(string motivoCobro, decimal monto, string vencimiento, string movimiento, string folioTGR, string rutCont) {
            SocialAseoWeb.PagosMacul.EnviaGiroRequest inValue = new SocialAseoWeb.PagosMacul.EnviaGiroRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.EnviaGiroRequestBody();
            inValue.Body.motivoCobro = motivoCobro;
            inValue.Body.monto = monto;
            inValue.Body.vencimiento = vencimiento;
            inValue.Body.movimiento = movimiento;
            inValue.Body.folioTGR = folioTGR;
            inValue.Body.rutCont = rutCont;
            SocialAseoWeb.PagosMacul.EnviaGiroResponse retVal = ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).EnviaGiro(inValue);
            return retVal.Body.EnviaGiroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaGiroResponse> SocialAseoWeb.PagosMacul.ServicioSoap.EnviaGiroAsync(SocialAseoWeb.PagosMacul.EnviaGiroRequest request) {
            return base.Channel.EnviaGiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaGiroResponse> EnviaGiroAsync(string motivoCobro, decimal monto, string vencimiento, string movimiento, string folioTGR, string rutCont) {
            SocialAseoWeb.PagosMacul.EnviaGiroRequest inValue = new SocialAseoWeb.PagosMacul.EnviaGiroRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.EnviaGiroRequestBody();
            inValue.Body.motivoCobro = motivoCobro;
            inValue.Body.monto = monto;
            inValue.Body.vencimiento = vencimiento;
            inValue.Body.movimiento = movimiento;
            inValue.Body.folioTGR = folioTGR;
            inValue.Body.rutCont = rutCont;
            return ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).EnviaGiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.PagosMacul.RecibePagoResponse SocialAseoWeb.PagosMacul.ServicioSoap.RecibePago(SocialAseoWeb.PagosMacul.RecibePagoRequest request) {
            return base.Channel.RecibePago(request);
        }
        
        public string RecibePago(string M2) {
            SocialAseoWeb.PagosMacul.RecibePagoRequest inValue = new SocialAseoWeb.PagosMacul.RecibePagoRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.RecibePagoRequestBody();
            inValue.Body.M2 = M2;
            SocialAseoWeb.PagosMacul.RecibePagoResponse retVal = ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).RecibePago(inValue);
            return retVal.Body.RecibePagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibePagoResponse> SocialAseoWeb.PagosMacul.ServicioSoap.RecibePagoAsync(SocialAseoWeb.PagosMacul.RecibePagoRequest request) {
            return base.Channel.RecibePagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibePagoResponse> RecibePagoAsync(string M2) {
            SocialAseoWeb.PagosMacul.RecibePagoRequest inValue = new SocialAseoWeb.PagosMacul.RecibePagoRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.RecibePagoRequestBody();
            inValue.Body.M2 = M2;
            return ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).RecibePagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse SocialAseoWeb.PagosMacul.ServicioSoap.EnviaCuadratura(SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest request) {
            return base.Channel.EnviaCuadratura(request);
        }
        
        public string EnviaCuadratura(string fecInforma) {
            SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest inValue = new SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.EnviaCuadraturaRequestBody();
            inValue.Body.fecInforma = fecInforma;
            SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse retVal = ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).EnviaCuadratura(inValue);
            return retVal.Body.EnviaCuadraturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse> SocialAseoWeb.PagosMacul.ServicioSoap.EnviaCuadraturaAsync(SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest request) {
            return base.Channel.EnviaCuadraturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.EnviaCuadraturaResponse> EnviaCuadraturaAsync(string fecInforma) {
            SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest inValue = new SocialAseoWeb.PagosMacul.EnviaCuadraturaRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.EnviaCuadraturaRequestBody();
            inValue.Body.fecInforma = fecInforma;
            return ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).EnviaCuadraturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse SocialAseoWeb.PagosMacul.ServicioSoap.RecibeCuadratura(SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest request) {
            return base.Channel.RecibeCuadratura(request);
        }
        
        public string RecibeCuadratura(string MR) {
            SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest inValue = new SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.RecibeCuadraturaRequestBody();
            inValue.Body.MR = MR;
            SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse retVal = ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).RecibeCuadratura(inValue);
            return retVal.Body.RecibeCuadraturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse> SocialAseoWeb.PagosMacul.ServicioSoap.RecibeCuadraturaAsync(SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest request) {
            return base.Channel.RecibeCuadraturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.RecibeCuadraturaResponse> RecibeCuadraturaAsync(string MR) {
            SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest inValue = new SocialAseoWeb.PagosMacul.RecibeCuadraturaRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.RecibeCuadraturaRequestBody();
            inValue.Body.MR = MR;
            return ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).RecibeCuadraturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.PagosMacul.HelloMyFriendResponse SocialAseoWeb.PagosMacul.ServicioSoap.HelloMyFriend(SocialAseoWeb.PagosMacul.HelloMyFriendRequest request) {
            return base.Channel.HelloMyFriend(request);
        }
        
        public string HelloMyFriend() {
            SocialAseoWeb.PagosMacul.HelloMyFriendRequest inValue = new SocialAseoWeb.PagosMacul.HelloMyFriendRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.HelloMyFriendRequestBody();
            SocialAseoWeb.PagosMacul.HelloMyFriendResponse retVal = ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).HelloMyFriend(inValue);
            return retVal.Body.HelloMyFriendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.HelloMyFriendResponse> SocialAseoWeb.PagosMacul.ServicioSoap.HelloMyFriendAsync(SocialAseoWeb.PagosMacul.HelloMyFriendRequest request) {
            return base.Channel.HelloMyFriendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.PagosMacul.HelloMyFriendResponse> HelloMyFriendAsync() {
            SocialAseoWeb.PagosMacul.HelloMyFriendRequest inValue = new SocialAseoWeb.PagosMacul.HelloMyFriendRequest();
            inValue.Body = new SocialAseoWeb.PagosMacul.HelloMyFriendRequestBody();
            return ((SocialAseoWeb.PagosMacul.ServicioSoap)(this)).HelloMyFriendAsync(inValue);
        }
    }
}
