//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class accesosEntities : DbContext
    {
        public accesosEntities()
            : base("name=accesosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<INAC_USUARIO> INAC_USUARIO { get; set; }
    
        public virtual ObjectResult<string> PA_ENCIP_DESENCRIP_DATOS_MVC(string dATO, string oPCION)
        {
            var dATOParameter = dATO != null ?
                new ObjectParameter("DATO", dATO) :
                new ObjectParameter("DATO", typeof(string));
    
            var oPCIONParameter = oPCION != null ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_ENCIP_DESENCRIP_DATOS_MVC", dATOParameter, oPCIONParameter);
        }
    
        public virtual ObjectResult<PA_VALIDA_USUARIO_WEB_Result> PA_VALIDA_USUARIO_WEB(Nullable<decimal> uSUA_CODIGO_SIST, string usuario, string llave, Nullable<decimal> opcion)
        {
            var uSUA_CODIGO_SISTParameter = uSUA_CODIGO_SIST.HasValue ?
                new ObjectParameter("USUA_CODIGO_SIST", uSUA_CODIGO_SIST) :
                new ObjectParameter("USUA_CODIGO_SIST", typeof(decimal));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var llaveParameter = llave != null ?
                new ObjectParameter("llave", llave) :
                new ObjectParameter("llave", typeof(string));
    
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_VALIDA_USUARIO_WEB_Result>("PA_VALIDA_USUARIO_WEB", uSUA_CODIGO_SISTParameter, usuarioParameter, llaveParameter, opcionParameter);
        }
    }
}
