//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_CONTRIBUYENTE
    {
        public decimal CON_ANO_CON { get; set; }
        public decimal CON_ROL_NUM { get; set; }
        public decimal CON_ROL_DV { get; set; }
        public Nullable<System.DateTime> CON_FEC_ING { get; set; }
        public Nullable<decimal> CON_NUM_FOLIO { get; set; }
        public decimal CON_RUT { get; set; }
        public string CON_DV { get; set; }
        public string CON_CALLE { get; set; }
        public string CON_NUMERO { get; set; }
        public Nullable<decimal> CON_MANZANA { get; set; }
        public Nullable<decimal> CON_PREDIO { get; set; }
        public string CON_VILLA { get; set; }
        public Nullable<decimal> CON_AVALUO { get; set; }
        public string CON_DESTINO { get; set; }
        public string CON_UBICACION { get; set; }
        public string CON_TIPO_CONT { get; set; }
        public string CON_SITUACION { get; set; }
        public Nullable<decimal> CON_POR_REB { get; set; }
        public string CON_ESTADO { get; set; }
        public string CON_OBSERV { get; set; }
        public Nullable<decimal> CON_CODCALLE { get; set; }
        public string CON_UNVECINAL { get; set; }
        public Nullable<decimal> CON_CODCAPRO { get; set; }
        public string CON_UNVECPRO { get; set; }
        public string CON_CALLEP { get; set; }
        public string CON_NUMEROP { get; set; }
        public string CON_TIPO_ENV { get; set; }
        public Nullable<decimal> CON_VILLA_R { get; set; }
        public Nullable<decimal> CON_VILLA_P { get; set; }
        public Nullable<decimal> CON_REGISTRO { get; set; }
        public string CON_ELIMINA { get; set; }
    }
}
