//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_CONVENIO
    {
        public decimal CON_ANO_CON { get; set; }
        public decimal CON_ROL_NUM { get; set; }
        public decimal CON_ROL_DV { get; set; }
        public decimal CON_CUOTA { get; set; }
        public Nullable<System.DateTime> CON_FEC_PRES { get; set; }
        public string CON_ESTADO { get; set; }
        public string CON_MARCA { get; set; }
        public string CON_GLOSA { get; set; }
        public Nullable<decimal> CON_PORCEN { get; set; }
        public Nullable<decimal> CON_NUM_DECRE { get; set; }
        public Nullable<System.DateTime> CON_FEC_DECRE { get; set; }
        public Nullable<decimal> CON_CODEX { get; set; }
        public Nullable<decimal> CON_FOLIO { get; set; }
    }
}
