//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_PAGOS
    {
        public decimal PAG_ANO_CON { get; set; }
        public decimal PAG_ROL_NUM { get; set; }
        public decimal PAG_ROL_DV { get; set; }
        public decimal PAG_CUOTA { get; set; }
        public string PAG_ESTADO { get; set; }
        public string PAG_TIPO { get; set; }
        public Nullable<System.DateTime> PAG_FEC_V { get; set; }
        public Nullable<System.DateTime> PAG_FEC_P { get; set; }
        public Nullable<System.DateTime> PAG_FEC_PRO { get; set; }
        public Nullable<decimal> PAG_VALOR { get; set; }
        public Nullable<decimal> PAG_IPC { get; set; }
        public Nullable<decimal> PAG_MULTA { get; set; }
        public Nullable<decimal> PAG_TOTAL { get; set; }
        public Nullable<decimal> PAG_TOTAL_RESP { get; set; }
        public Nullable<decimal> PAG_FOLIO { get; set; }
        public string PAG_MARCA { get; set; }
        public string PAG_CONVE { get; set; }
        public string PAG_ABONO { get; set; }
        public Nullable<decimal> PAG_TIPEX { get; set; }
    }
}
