//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenIngresoAseo
    {
        public string idSesion { get; set; }
        public decimal rolNum { get; set; }
        public decimal rolDv { get; set; }
        public string nOrden { get; set; }
        public string denominacion { get; set; }
        public decimal anio { get; set; }
        public decimal cuota { get; set; }
        public string fecVence { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> multa { get; set; }
        public Nullable<decimal> ipc { get; set; }
        public Nullable<decimal> total { get; set; }
        public string folio { get; set; }
    }
}
