//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INAC_USUARIO
    {
        public decimal USUA_CODIGO_SIST { get; set; }
        public string USUA_CODIGO { get; set; }
        public string USUA_PASSWORD { get; set; }
        public decimal USUA_RUT { get; set; }
        public string USUA_NOMBRE { get; set; }
        public string USUA_DV { get; set; }
        public string USUA_CARGO { get; set; }
        public decimal USUA_COD_PERFIL { get; set; }
        public Nullable<System.DateTime> USUA_FECHA_INI { get; set; }
        public Nullable<System.DateTime> USUA_FECHA_FIN { get; set; }
        public string USUA_VIGENCIA { get; set; }
        public Nullable<System.DateTime> USUA_FECHA_PASSW { get; set; }
        public string USUA_UBICACION { get; set; }
        public Nullable<decimal> USUA_ESTA { get; set; }
        public string USUA_PERM_GRABAR { get; set; }
        public string USUA_PERM_ELIMINAR { get; set; }
        public string USUA_CCOSTO { get; set; }
        public string USUA_CCOSTO2 { get; set; }
        public string USUA_CCOSTO3 { get; set; }
        public string USUA_CCOSTO4 { get; set; }
        public string USUA_CCOSTO5 { get; set; }
        public string USUA_COD_CAJERO { get; set; }
        public string USUA_TOKEN { get; set; }
    }
}
