//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenIngresoAseo
    {
        public string idSesion { get; set; }
        public string rut { get; set; }
        public string dv { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public decimal rolNum { get; set; }
        public decimal rolDv { get; set; }
        public string telefono { get; set; }
        public string eMail { get; set; }
        public string fecPago { get; set; }
        public string cuidad { get; set; }
        public string nOrden { get; set; }
        public string tipoTributo { get; set; }
        public string unidadGiradora { get; set; }
        public string tipoPago { get; set; }
        public string tipoCuota { get; set; }
        public string nCuotas { get; set; }
        public string tipoTransaccion { get; set; }
        public string digTarjeta { get; set; }
        public string codAutoriza { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> ipc { get; set; }
        public Nullable<decimal> multa { get; set; }
        public Nullable<decimal> aPagar { get; set; }
    }
}
