//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPKCC_TRANSAC_ASEO
    {
        public decimal ASE_ROL_NUM { get; set; }
        public decimal ASE_ROL_DV { get; set; }
        public decimal ASE_ANIO { get; set; }
        public decimal ASE_CUOTA { get; set; }
        public decimal ASE_VALOR { get; set; }
        public decimal ASE_IPC { get; set; }
        public decimal ASE_MULTA { get; set; }
        public decimal ASE_TOTAL { get; set; }
        public decimal ASE_FOLIO_TRANS { get; set; }
        public string ASE_ESTADO_TRANS { get; set; }
        public string ASE_FEC_PAG { get; set; }
        public string ASE_FEC_VEN { get; set; }
        public string ASE_EMAIL { get; set; }
        public string ASE_TELEFONO { get; set; }
        public Nullable<decimal> ASE_FOLIO_TESMU { get; set; }
        public string ASE_TIPO_PAGO { get; set; }
        public string ASE_NUM_CUOTA { get; set; }
        public string ASE_TIPO_TRANS { get; set; }
        public string ASE_DIG_TARJETA { get; set; }
        public Nullable<decimal> ASE_ID_SESION { get; set; }
        public string ASE_COD_AUTORIZA { get; set; }
        public Nullable<System.DateTime> ASE_FEC_CREA { get; set; }
        public string ASE_ENVIA_MAIL { get; set; }
    }
}
