//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPKCC_FOLIOS_ASIGNADOS
    {
        public string FA_LLAVE1 { get; set; }
        public string FA_LLAVE2 { get; set; }
        public string FA_LLAVE3 { get; set; }
        public string FA_LLAVE4 { get; set; }
        public decimal FA_FOLIO_TRANS { get; set; }
        public string FA_EMAIL { get; set; }
        public string FA_TELEFONO { get; set; }
        public string FA_TOKEN { get; set; }
        public string FA_ENVIO_MAIL { get; set; }
        public Nullable<System.DateTime> FA_CREACION { get; set; }
    }
}
