//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_OrdenIngresoAseo
    {
        public string idSesion { get; set; }
        public string rut { get; set; }
        public string dv { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string depto { get; set; }
        public string block { get; set; }
        public string direccion2 { get; set; }
        public string depto2 { get; set; }
        public string block2 { get; set; }
        public decimal rolNum { get; set; }
        public decimal rolDv { get; set; }
        public string telefono { get; set; }
        public string eMail { get; set; }
        public string fecRecepcion { get; set; }
        public string nOrden { get; set; }
        public string estado { get; set; }
        public string ch { get; set; }
        public decimal uv { get; set; }
        public string periodo { get; set; }
        public string cuotas { get; set; }
        public string respo { get; set; }
        public Nullable<decimal> folioRSH { get; set; }
        public Nullable<decimal> fecha_RSH { get; set; }
        public Nullable<decimal> Tramo { get; set; }
        public Nullable<decimal> numeroD { get; set; }
        public Nullable<decimal> numero2 { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Origen { get; set; }
    }
}
