//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_DetalleArchivo
    {
        public decimal SD_anio { get; set; }
        public decimal SD_RolA { get; set; }
        public decimal SD_RolB { get; set; }
        public decimal SD_Cuota { get; set; }
        public string SD_Arch_1 { get; set; }
        public string SD_Arch_2 { get; set; }
        public string SD_Estado { get; set; }
    }
}
