//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_PARTICULAR_ARCHIVOS_DETALLE
    {
        public decimal TPAD_ANO { get; set; }
        public string TPAD_MANZANA { get; set; }
        public decimal TPAD_PREDIO { get; set; }
        public string TPAD_CUOTA { get; set; }
        public string TPAD_CORREO { get; set; }
        public Nullable<decimal> TPAD_FONO { get; set; }
        public string TPAD_NOMBRE_ARCHIVO { get; set; }
        public string TPAD_FECHA_INGRESO { get; set; }
        public string TPAD_HORA_INGRESO { get; set; }
        public Nullable<int> TPAD_ESTADO { get; set; }
        public string TPAD_ESTADO_DESCRIPCION { get; set; }
        public Nullable<int> TPAD_CLASIFICACION { get; set; }
    }
}
