//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_PARTICULAR_ARCHIVOS_ENCABEZADO
    {
        public decimal TPAE_ANO { get; set; }
        public string TPAE_MANZANA { get; set; }
        public decimal TPAE_PREDIO { get; set; }
        public string TPAE_CUOTA { get; set; }
        public string TPAE_CORREO { get; set; }
        public Nullable<decimal> TPAE_FONO { get; set; }
        public string TPAE_FECHA_INGRESO { get; set; }
        public string TPAE_HORA_INGRESO { get; set; }
        public Nullable<int> TPAE_ESTADO { get; set; }
        public string TPAE_USUARIO { get; set; }
        public string TPAE_ESTADO_PAGO { get; set; }
        public string TPAE_FECHA_PAGO { get; set; }
    }
}
