//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class tesoreria2008Entities : DbContext
    {
        public tesoreria2008Entities()
            : base("name=tesoreria2008Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ATETIPOPAGO> ATETIPOPAGO { get; set; }
    
        public virtual ObjectResult<PA_OBTIENE_DATOS_WS_SUBDERE_Result> PA_OBTIENE_DATOS_WS_SUBDERE(Nullable<decimal> tIPO_DOC, Nullable<decimal> fOLIO)
        {
            var tIPO_DOCParameter = tIPO_DOC.HasValue ?
                new ObjectParameter("TIPO_DOC", tIPO_DOC) :
                new ObjectParameter("TIPO_DOC", typeof(decimal));
    
            var fOLIOParameter = fOLIO.HasValue ?
                new ObjectParameter("FOLIO", fOLIO) :
                new ObjectParameter("FOLIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_OBTIENE_DATOS_WS_SUBDERE_Result>("PA_OBTIENE_DATOS_WS_SUBDERE", tIPO_DOCParameter, fOLIOParameter);
        }
    }
}
