//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGR_ENVIA_GIRO
    {
        public string TGR_CODE { get; set; }
        public string TGR_MSG_DESC { get; set; }
        public string TGR_FROM { get; set; }
        public string TGR_REF { get; set; }
        public string TGR_DATETIME { get; set; }
        public string TGR_ID_EXT { get; set; }
        public string TGR_RUT { get; set; }
        public string TGR_DV { get; set; }
        public string TGR_FORMULARIO { get; set; }
        public string TGR_FOLIO { get; set; }
        public string TGR_VENCIMIENTO { get; set; }
        public string TGR_MONEDA { get; set; }
        public string TGR_MONTO { get; set; }
        public string TGR_MOVIMIENTO { get; set; }
        public string TGR_XML { get; set; }
        public string TGR_RESPUESTA { get; set; }
        public string TGR_ESTADO { get; set; }
    }
}
