//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGR_RECIBE_PAGO
    {
        public string TGR_CODE { get; set; }
        public string TGR_MSG_DESC { get; set; }
        public string TGR_VERSION { get; set; }
        public string TGR_FROM_ADDRESS { get; set; }
        public string TGR_TO_ADDRESS { get; set; }
        public string TGR_REF_ADDRESS { get; set; }
        public string TGR_DATETIME { get; set; }
        public string TGR_NUMBER { get; set; }
        public string TGR_ID_EXT { get; set; }
        public string TGR_STATUS { get; set; }
        public string TGR_ID_OPERACION { get; set; }
        public string TGR_ID_TRANSACCION { get; set; }
        public string TGR_RUT { get; set; }
        public string TGR_FORMULARIO { get; set; }
        public string TGR_FOLIO { get; set; }
        public string TGR_VENCIMIENTO { get; set; }
        public string TGR_MONTO { get; set; }
        public string TGR_COD_BANCO_PAGO { get; set; }
        public string TGR_NOMBRE_BANCO_PAGO { get; set; }
        public string TGR_FECHA_PAGO { get; set; }
        public string TGR_RESULTADO { get; set; }
        public string TGR_TIPO_PAGO { get; set; }
        public string TGR_XML { get; set; }
    }
}
