//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBPAY
    {
        public string TBK_TIPO_TRANSACCION { get; set; }
        public string TBK_RESPUESTA { get; set; }
        public string TBK_ORDEN_COMPRA { get; set; }
        public string TBK_ID_SESION { get; set; }
        public string TBK_CODIGO_AUTORIZACION { get; set; }
        public Nullable<decimal> TBK_MONTO { get; set; }
        public string TBK_FINAL_NUMERO_TARJETA { get; set; }
        public string TBK_FECHA_EXPIRACION { get; set; }
        public string TBK_FECHA_CONTABLE { get; set; }
        public string TBK_FECHA_TRANSACCION { get; set; }
        public string TBK_HORA_TRANSACCION { get; set; }
        public string TBK_ID_TRANSACCION { get; set; }
        public string TBK_TIPO_PAGO { get; set; }
        public string TBK_NUMERO_CUOTAS { get; set; }
        public string TBK_MAC { get; set; }
        public string TBK_TASA_INTERES_MAX { get; set; }
    }
}
