//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialAseoWeb.InformaPagoSubdere {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformaPagoSubdere.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento InformaPagoSubdereResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformaPagoSubdere", ReplyAction="*")]
        SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse InformaPagoSubdere(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformaPagoSubdere", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse> InformaPagoSubdereAsync(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformaPagoSubdereRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformaPagoSubdere", Namespace="http://tempuri.org/", Order=0)]
        public SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequestBody Body;
        
        public InformaPagoSubdereRequest() {
        }
        
        public InformaPagoSubdereRequest(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformaPagoSubdereRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal folioTbk;
        
        public InformaPagoSubdereRequestBody() {
        }
        
        public InformaPagoSubdereRequestBody(decimal folioTbk) {
            this.folioTbk = folioTbk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformaPagoSubdereResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformaPagoSubdereResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponseBody Body;
        
        public InformaPagoSubdereResponse() {
        }
        
        public InformaPagoSubdereResponse(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformaPagoSubdereResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InformaPagoSubdereResult;
        
        public InformaPagoSubdereResponseBody() {
        }
        
        public InformaPagoSubdereResponseBody(string InformaPagoSubdereResult) {
            this.InformaPagoSubdereResult = InformaPagoSubdereResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : SocialAseoWeb.InformaPagoSubdere.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SocialAseoWeb.InformaPagoSubdere.Service1Soap>, SocialAseoWeb.InformaPagoSubdere.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse SocialAseoWeb.InformaPagoSubdere.Service1Soap.InformaPagoSubdere(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest request) {
            return base.Channel.InformaPagoSubdere(request);
        }
        
        public string InformaPagoSubdere(decimal folioTbk) {
            SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest inValue = new SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest();
            inValue.Body = new SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequestBody();
            inValue.Body.folioTbk = folioTbk;
            SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse retVal = ((SocialAseoWeb.InformaPagoSubdere.Service1Soap)(this)).InformaPagoSubdere(inValue);
            return retVal.Body.InformaPagoSubdereResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse> SocialAseoWeb.InformaPagoSubdere.Service1Soap.InformaPagoSubdereAsync(SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest request) {
            return base.Channel.InformaPagoSubdereAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereResponse> InformaPagoSubdereAsync(decimal folioTbk) {
            SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest inValue = new SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequest();
            inValue.Body = new SocialAseoWeb.InformaPagoSubdere.InformaPagoSubdereRequestBody();
            inValue.Body.folioTbk = folioTbk;
            return ((SocialAseoWeb.InformaPagoSubdere.Service1Soap)(this)).InformaPagoSubdereAsync(inValue);
        }
    }
}
